# Generated by Django 3.2.7 on 2021-09-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0002_auto_20210921_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='verified',
            field=models.BooleanField(default=False, help_text='Verified cricles are also known as official communities', verbose_name='verified circle'),
        ),
    ]
